services:
  frontend:
    build:
      context: .
      args:
        # Build-time Vite envs (will be injected into the build)
        VITE_API_URL: ${VITE_API_URL}
    image: home-cycle-home:latest
    container_name: home-cycle-home
    ports:
      - "${PORT:-8080}:80"
    env_file:
      - .env
    #