/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthSigninRouteImport } from './routes/auth/Signin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedComptesIndexRouteImport } from './routes/_authenticated/comptes/index'
import { Route as AuthenticatedCarteIndexRouteImport } from './routes/_authenticated/carte/index'
import { Route as AuthenticatedComptesCreateRouteImport } from './routes/_authenticated/comptes/create'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/Signin',
  path: '/Signin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComptesIndexRoute =
  AuthenticatedComptesIndexRouteImport.update({
    id: '/comptes/',
    path: '/comptes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCarteIndexRoute = AuthenticatedCarteIndexRouteImport.update({
  id: '/carte/',
  path: '/carte/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComptesCreateRoute =
  AuthenticatedComptesCreateRouteImport.update({
    id: '/comptes/create',
    path: '/comptes/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/Signin': typeof AuthSigninRoute
  '/': typeof AuthenticatedIndexRoute
  '/comptes/create': typeof AuthenticatedComptesCreateRoute
  '/carte': typeof AuthenticatedCarteIndexRoute
  '/comptes': typeof AuthenticatedComptesIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/Signin': typeof AuthSigninRoute
  '/': typeof AuthenticatedIndexRoute
  '/comptes/create': typeof AuthenticatedComptesCreateRoute
  '/carte': typeof AuthenticatedCarteIndexRoute
  '/comptes': typeof AuthenticatedComptesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/Signin': typeof AuthSigninRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/comptes/create': typeof AuthenticatedComptesCreateRoute
  '/_authenticated/carte/': typeof AuthenticatedCarteIndexRoute
  '/_authenticated/comptes/': typeof AuthenticatedComptesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/dashboard'
    | '/auth/Signin'
    | '/'
    | '/comptes/create'
    | '/carte'
    | '/comptes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/dashboard'
    | '/auth/Signin'
    | '/'
    | '/comptes/create'
    | '/carte'
    | '/comptes'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/auth/Signin'
    | '/_authenticated/'
    | '/_authenticated/comptes/create'
    | '/_authenticated/carte/'
    | '/_authenticated/comptes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/Signin': {
      id: '/auth/Signin'
      path: '/Signin'
      fullPath: '/auth/Signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comptes/': {
      id: '/_authenticated/comptes/'
      path: '/comptes'
      fullPath: '/comptes'
      preLoaderRoute: typeof AuthenticatedComptesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/carte/': {
      id: '/_authenticated/carte/'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof AuthenticatedCarteIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comptes/create': {
      id: '/_authenticated/comptes/create'
      path: '/comptes/create'
      fullPath: '/comptes/create'
      preLoaderRoute: typeof AuthenticatedComptesCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedComptesCreateRoute: typeof AuthenticatedComptesCreateRoute
  AuthenticatedCarteIndexRoute: typeof AuthenticatedCarteIndexRoute
  AuthenticatedComptesIndexRoute: typeof AuthenticatedComptesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedComptesCreateRoute: AuthenticatedComptesCreateRoute,
  AuthenticatedCarteIndexRoute: AuthenticatedCarteIndexRoute,
  AuthenticatedComptesIndexRoute: AuthenticatedComptesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
